### ISSUE TITLE
Improve default osm dark mode

### ISSUE THREAD

**Issue by Nekzuris** [deevroman/better-osm-org#106]
The tooltip is white in dark mode, see https://github.com/openstreetmap/openstreetmap-website/issues/5329#issuecomment-2487203946
I should PR a fix directly to openstreetmap-website but idk how to integrate it properly with their .scss and test it.

**Comment by Nekzuris** [comment]
I also made a more modern search bar without the rectangular background and transparency like this:
![image](https://github.com/user-attachments/assets/be88e6c6-b9a2-4665-b0fe-f6144370d7ab)

my css, works on default but needs integration with your resizable sidebar:
```css
#sidebar, .bg-body-secondary {
    background: none !important;
}    
#sidebar > div:not(:first-child) {
    background-color: rgba(var(--bs-body-bg-rgb), var(--bs-bg-opacity)) !important;
}
.search_form .form-control {
    background-color: rgba(255,255,255,.75);
}
@media(prefers-color-scheme: dark) {
    .search_form .form-control {
        background-color: rgba(0,0,0,.75) !important;
    }
}
```
